---
default:
  threads: 6
  producer_type: BaseProducer
  producer_config:
    bootstrap.servers: localhost:9092
    queue.buffering.max.ms: 100
    queue.buffering.max.messages: 1000000

scenarios:
  hydra:
    repeat_times: 5
    repeat_pause: 10
    topic: hydra-transactions
    message_size: 10
    message_count: 1000
    message_file: ../hydra/integration-test/transactions.blob

  